name: Build Release APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk wget unzip git

      - name: Install Android SDK Command-line Tools
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip commandlinetools-linux-11076708_latest.zip
          rm commandlinetools-linux-11076708_latest.zip
          mkdir latest
          mv cmdline-tools/* latest/
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk --licenses
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk \
            "platform-tools" "platforms;android-31" "build-tools;33.0.2" "ndk;23.1.7779620"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > my-release-key.keystore

      - name: Build Release APK
        run: |
          buildozer android release

      - name: Sign APK
        run: |
          jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 \
            -keystore my-release-key.keystore \
            -storepass "${{ secrets.KEYSTORE_PASSWORD }}" \
            -keypass "${{ secrets.KEY_PASSWORD }}" \
            bin/*-release-unsigned.apk "${{ secrets.KEY_ALIAS }}"

      - name: Align APK
        run: |
          $HOME/android-sdk/build-tools/33.0.2/zipalign -v 4 \
            bin/*-release-unsigned.apk bin/app-release.apk

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: bin/app-release.apk
